"use client";

import { useState } from "react";
import type { SimulationResult } from "@/lib/simulation/schema";
import { ScoreCard } from "./ScoreCard";

interface SimulationDashboardProps {
  result: SimulationResult;
  onReSimulateWithEvidence: (evidence: string) => void;
  reSimulating?: boolean;
  decision: "BUILD" | "DONT_BUILD" | null;
  onSelectDecision: (decision: "BUILD" | "DONT_BUILD") => void;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl bg-genie-card p-5 ring-1 ring-white/5">
      <h3 className="text-sm font-semibold uppercase tracking-wide text-genie-accent">{title}</h3>
      <div className="mt-2 text-sm leading-relaxed text-slate-200">{children}</div>
    </div>
  );
}

export function SimulationDashboard({
  result,
  onReSimulateWithEvidence,
  reSimulating,
  decision,
  onSelectDecision,
}: SimulationDashboardProps) {
  const { report, engine } = result;
  const [evidenceInput, setEvidenceInput] = useState("");

  function handleReSimulate(e: React.FormEvent) {
    e.preventDefault();
    if (evidenceInput.trim()) {
      onReSimulateWithEvidence(evidenceInput.trim());
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-xl font-bold text-slate-100">Decision Dashboard</h2>
          <p className="text-xs text-slate-400 italic mt-0.5">Scores are signals, not &quot;AI truth.&quot;</p>
        </div>
        <span
          className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400 ring-1 ring-white/10"
          title={
            engine === "llm"
              ? "Generated by the configured language model."
              : "Generated by Genie's built-in offline analysis engine."
          }
        >
          {engine === "llm" ? "LLM engine" : "Offline engine"}
        </span>
      </div>

      <Section title="Summary">{report.summary}</Section>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
        <ScoreCard label="Desirability" value={report.scores.desirability} hint="Do people want this?" />
        <ScoreCard label="Feasibility" value={report.scores.feasibility} hint="Can it be built?" />
        <ScoreCard label="Differentiation" value={report.scores.differentiation} hint="Distinct from alternatives?" />
        <ScoreCard label="Execution Risk" value={report.scores.executionRisk} hint="Higher = safer" />
        <ScoreCard label="Confidence" value={report.scores.confidence} hint="Evidence vs assumptions" />
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-5">
          <h3 className="text-xs font-bold uppercase tracking-wide text-amber-400">Find the Weak Assumption</h3>
          <p className="mt-2 text-sm font-medium leading-relaxed text-slate-100">
            &quot;{report.weakAssumption}&quot;
          </p>
        </div>

        <div className="rounded-xl border border-genie-accent/40 bg-genie-accent/10 p-5">
          <h3 className="text-xs font-bold uppercase tracking-wide text-genie-accent">Design an Experiment</h3>
          <p className="mt-2 text-sm leading-relaxed text-slate-100">
            {report.experimentDesign}
          </p>
        </div>
      </div>

      <form onSubmit={handleReSimulate} className="rounded-xl bg-genie-card p-5 ring-1 ring-white/10 space-y-3">
        <div className="flex flex-col gap-1">
          <h3 className="text-sm font-semibold uppercase tracking-wide text-genie-accent">
            Real-World Data &amp; Re-Simulation
          </h3>
          <p className="text-xs text-slate-400">
            Ran an experiment or spoke to users? Enter evidence here to replace assumptions and update scores.
          </p>
        </div>
        <textarea
          value={evidenceInput}
          onChange={(e) => setEvidenceInput(e.target.value)}
          rows={2}
          placeholder="e.g. Interviewed 10 users; 7 confirmed willingness to pay $20/mo and built a waitlist of 45 people."
          className="w-full resize-y rounded-xl bg-genie-bg p-3 text-sm text-slate-100 placeholder:text-slate-500 ring-1 ring-white/10 focus:outline-none focus:ring-2 focus:ring-genie-accent"
        />
        <div className="flex justify-end">
          <button
            type="submit"
            disabled={!evidenceInput.trim() || reSimulating}
            className="rounded-xl bg-genie-accent/20 px-4 py-2 text-xs font-semibold text-genie-accent ring-1 ring-genie-accent/40 transition hover:bg-genie-accent/30 disabled:opacity-40"
          >
            {reSimulating ? "Re-simulating…" : "Re-simulate Idea with Evidence"}
          </button>
        </div>
      </form>

      <div className="rounded-xl border border-genie-accent/40 bg-genie-accent/10 p-5">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-genie-accent">Recommendation</h3>
        <p className="mt-2 text-sm leading-relaxed text-slate-100">{report.recommendation}</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Section title="Target user">{report.targetUser}</Section>
        <Section title="Problem clarity">{report.problemClarity}</Section>
        <Section title="Differentiation">{report.differentiation}</Section>
        <Section title="Market demand">{report.marketDemand}</Section>
      </div>

      <Section title="MVP suggestion">{report.mvpSuggestion}</Section>

      <div className="grid gap-4 md:grid-cols-2">
        <Section title="Risks">
          <ul className="list-disc space-y-2 pl-5 marker:text-genie-bad">
            {report.risks.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </Section>
        <Section title="Next steps">
          <ol className="list-decimal space-y-2 pl-5 marker:text-genie-good">
            {report.nextSteps.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ol>
        </Section>
      </div>

      {/* Make a Decision Section */}
      <div className="rounded-xl border border-white/10 bg-genie-card p-6 space-y-4">
        <div className="text-center">
          <h3 className="text-lg font-bold text-slate-100">Make a Decision</h3>
          <p className="text-xs text-slate-400 mt-1">Based on the simulation signal and evidence, what is your call?</p>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <button
            type="button"
            onClick={() => onSelectDecision("BUILD")}
            className={`rounded-xl p-4 text-center ring-1 transition ${
              decision === "BUILD"
                ? "bg-genie-good/20 ring-genie-good text-genie-good"
                : "bg-white/5 ring-white/10 text-slate-200 hover:bg-white/10"
            }`}
          >
            <div className="text-lg font-bold">BUILD</div>
            <div className="text-xs opacity-80 mt-1">Confidence ↑ · Risk ↓ · Evidence ↑</div>
          </button>

          <button
            type="button"
            onClick={() => onSelectDecision("DONT_BUILD")}
            className={`rounded-xl p-4 text-center ring-1 transition ${
              decision === "DONT_BUILD"
                ? "bg-genie-bad/20 ring-genie-bad text-genie-bad"
                : "bg-white/5 ring-white/10 text-slate-200 hover:bg-white/10"
            }`}
          >
            <div className="text-lg font-bold">DON&apos;T BUILD</div>
            <div className="text-xs opacity-80 mt-1">Money saved · Time saved</div>
          </button>
        </div>

        {decision === "BUILD" && (
          <div className="rounded-xl bg-genie-good/10 p-4 border border-genie-good/30 text-sm text-genie-good text-center">
            ✓ Decision set to <strong>BUILD</strong>. Proceed to the <strong>Action Plan</strong> below to start execution!
          </div>
        )}

        {decision === "DONT_BUILD" && (
          <div className="rounded-xl bg-genie-bad/10 p-4 border border-genie-bad/30 text-sm text-slate-200 text-center space-y-1">
            <div className="font-semibold text-genie-bad">✓ Decision set to DON&apos;T BUILD</div>
            <p className="text-xs text-slate-300">
              You saved weeks of engineering effort and capital! Consider pivoting the intent or exploring a different high-signal idea.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
