import type { SimulationResult } from "@/lib/simulation/schema";
import { ScoreCard } from "./ScoreCard";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl bg-genie-card p-5 ring-1 ring-white/5">
      <h3 className="text-sm font-semibold uppercase tracking-wide text-genie-accent">{title}</h3>
      <div className="mt-2 text-sm leading-relaxed text-slate-200">{children}</div>
    </div>
  );
}

export function SimulationDashboard({ result }: { result: SimulationResult }) {
  const { report, engine } = result;
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-lg font-semibold text-slate-100">Simulation report</h2>
        <span
          className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400 ring-1 ring-white/10"
          title={
            engine === "llm"
              ? "Generated by the configured language model."
              : "Generated by Genie's built-in offline analysis engine (no API key configured)."
          }
        >
          {engine === "llm" ? "LLM engine" : "Offline engine"}
        </span>
      </div>

      <Section title="Summary">{report.summary}</Section>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <ScoreCard label="Clarity" value={report.scores.clarity} hint="How clear the idea is" />
        <ScoreCard label="Practicality" value={report.scores.practicality} hint="Can it realistically be built" />
        <ScoreCard label="Opportunity" value={report.scores.opportunity} hint="Size of the upside" />
        <ScoreCard label="Safety" value={report.scores.risk} hint="Higher = lower risk" />
      </div>

      <div className="rounded-xl border border-genie-accent/40 bg-genie-accent/10 p-5">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-genie-accent">Recommendation</h3>
        <p className="mt-2 text-sm leading-relaxed text-slate-100">{report.recommendation}</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Section title="Target user">{report.targetUser}</Section>
        <Section title="Problem clarity">{report.problemClarity}</Section>
        <Section title="Differentiation">{report.differentiation}</Section>
        <Section title="Market demand">{report.marketDemand}</Section>
      </div>

      <Section title="MVP suggestion">{report.mvpSuggestion}</Section>

      <div className="grid gap-4 md:grid-cols-2">
        <Section title="Risks">
          <ul className="list-disc space-y-2 pl-5 marker:text-genie-bad">
            {report.risks.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </Section>
        <Section title="Next steps">
          <ol className="list-decimal space-y-2 pl-5 marker:text-genie-good">
            {report.nextSteps.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ol>
        </Section>
      </div>
    </div>
  );
}
